import { RunResult } from '@/types'

export const DEMO_RUN: RunResult = {
  run: {
    name: 'Sprint 42 — Checkout QA',
    url: 'https://demo.mystore.com',
    tester: 'Claude (automated)',
    date: '2025-03-24T12:00:00Z',
  },
  summary: { passed: 2, failed: 1, partial: 1, total_findings: 4, by_severity: { critical: 1, high: 1, medium: 1, low: 1 } },
  test_cases: [
    {
      id: 'TC-01',
      title: 'User completes checkout with saved card',
      status: 'FAIL',
      steps_executed: 6,
      expected_outcome: 'Order confirmation screen with order number',
      actual_outcome: "Error toast appears after clicking 'Place order' — no message text visible",
      screenshot_base64: '',
    },
    {
      id: 'TC-02',
      title: 'User updates email in account settings',
      status: 'PASS',
      steps_executed: 4,
      expected_outcome: 'Success message shown, email updated in header',
      actual_outcome: 'Email updated successfully with green toast confirmation',
      screenshot_base64: '',
    },
    {
      id: 'TC-03',
      title: 'User filters products by category',
      status: 'PARTIAL',
      steps_executed: 3,
      expected_outcome: 'Product grid updates without page reload',
      actual_outcome: 'Filters work but loading state is missing — grid flashes blank for ~300ms',
      screenshot_base64: '',
    },
    {
      id: 'TC-04',
      title: 'User resets password via email link',
      status: 'PASS',
      steps_executed: 5,
      expected_outcome: 'Password reset, redirected to login',
      actual_outcome: 'Flow completes correctly',
      screenshot_base64: '',
    },
  ],
  findings: [
    {
      id: 'F-01',
      title: 'Fix invisible error message on checkout failure',
      severity: 'critical',
      category: 'Bug',
      tc_id: 'TC-01',
      description: "When 'Place order' is clicked with a declined card, an error toast appears but contains no text. The user cannot understand what went wrong or how to recover.",
      steps: ['Navigate to /checkout', 'Add item to cart', 'Select saved card', "Click 'Place order'"],
      expected: "Error toast with message: 'Payment declined — please try another card'",
      actual: 'Empty toast with no text rendered',
      acceptance: [
        'Error message displayed within 500ms of failure',
        'Message text is visible and descriptive',
        'User is offered a recovery path (try another card)',
      ],
      screenshot_base64: '',
    },
    {
      id: 'F-02',
      title: 'Add loading state to product filter interactions',
      severity: 'medium',
      category: 'UX',
      tc_id: 'TC-03',
      description: 'Applying a product filter causes the grid to briefly flash blank before updating. There is no skeleton or spinner, making the UI feel broken during the 300ms transition.',
      steps: ['Navigate to /products', 'Click any category filter'],
      expected: 'Skeleton loader or spinner shown during filter application',
      actual: 'Grid turns blank for ~300ms with no feedback',
      acceptance: [
        'Loading state shown immediately on filter click',
        'Transition duration under 250ms on fast connections',
      ],
      screenshot_base64: '',
    },
    {
      id: 'F-03',
      title: 'Normalise heading font weights across product pages',
      severity: 'low',
      category: 'Design',
      tc_id: 'TC-03',
      description: 'Product card titles use font-weight: 700 on listing pages but font-weight: 400 on the detail page. This inconsistency breaks visual hierarchy continuity across the flow.',
      steps: ['View /products grid', 'Click into any product detail'],
      expected: 'Consistent heading weight (700) across listing and detail views',
      actual: 'Listing: 700, Detail: 400',
      acceptance: ['Heading weights consistent across all product page variants'],
      screenshot_base64: '',
    },
    {
      id: 'F-04',
      title: 'Add visible focus styles to all interactive elements',
      severity: 'high',
      category: 'Accessibility',
      tc_id: 'TC-02',
      description: 'Tab navigation through the account settings form reveals that several inputs and buttons have no visible focus ring. Keyboard-only users cannot determine which element is active.',
      steps: ['Navigate to /account/settings', 'Tab through the form fields'],
      expected: 'Visible focus ring on all interactive elements',
      actual: 'No focus indicator on 4 of 7 form fields and both action buttons',
      acceptance: [
        'Focus ring visible on all inputs, selects, and buttons',
        'Focus colour meets 3:1 contrast ratio against surrounding bg',
      ],
      screenshot_base64: '',
    },
  ],
}
